-- 코드를 작성해주세요
SELECT SUM(SCORE) AS 'SOCRE', HR_EMPLOYEES.EMP_NO, 
HR_EMPLOYEES.EMP_NAME, HR_EMPLOYEES.POSITION, HR_EMPLOYEES.EMAIL
FROM HR_EMPLOYEES
JOIN HR_GRADE ON HR_EMPLOYEES.EMP_NO = HR_GRADE.EMP_NO
GROUP BY HR_EMPLOYEES.EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1